version: '3'

services:

  test_web:
    container_name: test_web
    build: ./docker-file/web/
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/
      - ./docker-file/web/000-default.conf:/etc/apache2/sites-available/000-default.conf
  test_db:
    container_name: test_mysql
    image: mysql:8.0
    restart: unless-stopped
    tty: true
    ports:
        - "3306:3306"
    environment:
        MYSQL_DATABASE: test_task
        MYSQL_USER: laravel
        MYSQL_PASSWORD: test_password
        MYSQL_ROOT_PASSWORD: root_password

  test_phpmyadmin:
    container_name: test_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
    - '8888:80'
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=db
    depends_on:
    - test_db
